#配置端口号
server:
  port: 8081
  # 添加数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bm-book
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.alibaba.druid.proxy.DruidDriver
    username: root
    password: Zzz116540503
  application:
    name: BM-BOOK-SERVICE
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public