# 配置端口号
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bm-book
    username: root
    password: 1234567890
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: bm-book-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
logging:
  level:
    java.com.etoak.java.service.impl: debug
    java.com.etoak.java.feign: debug